#' Newton-Raphson Maximum Likelihood Estimation with Visualization
#'
#' @param x0 Numeric. The initial guess for the parameter value to start the Newton-Raphson iterations.
#' @param delta Numeric. A small step size used for numerical approximation of derivatives. Default is 0.001.
#' @param llik Function. A log-likelihood function defined by the user, which takes the parameter as an argument
#'   and returns the log-likelihood value.
#' @param xrange Numeric vector. A range of values (c(min, max)) over which the log-likelihood and its
#'   derivative are plotted.
#' @param parameter Character. The name of the parameter being estimated. Used for axis labels in the plots.
#'
#' @return A list containing:
#' \item{x}{Numeric vector. The sequence of parameter estimates generated by the Newton-Raphson algorithm.}
#' \item{y}{Numeric vector. The values of the derivative of the log-likelihood function at each estimate.}
#'
#' @export
#'
#' @examples
#' # Define a log-likelihood function (e.g., for a normal distribution)
#' ll <- function(mu) sum(dnorm(c(1, 2, 3), mean = mu, sd = 1, log = TRUE))
#'
#' # Run the Newton-Raphson algorithm with visualization
#' myNRML(0, delta = 0.001, llik = ll, xrange = c(-1, 4), parameter = "mu")

myNRML <- function(x0, delta = 0.001, llik, xrange, parameter = "param") {
  # Ensure llik is vectorized
  llikV <- Vectorize(llik)

  # Define the first derivative (f)
  f <- function(x) (llikV(x + delta) - llikV(x)) / delta

  # Define the second derivative (fdash)
  fdash <- function(x) (f(x + delta) - f(x)) / delta

  # Initialize Newton-Raphson variables
  d <- 1000
  i <- 0
  x <- numeric()
  y <- numeric()
  x[1] <- x0
  y[1] <- f(x[1])

  while (d > delta & i < 100) {
    i <- i + 1
    x[i + 1] <- x[i] - f(x[i]) / fdash(x[i])
    y[i + 1] <- f(x[i + 1])
    d <- abs(y[i + 1])
  }

  # Set up plotting
  graphics::layout(matrix(1:2, nrow = 1, ncol = 2, byrow = TRUE), widths = c(1, 2))

  # Correctly handle the curve function
  graphics::curve(
    expr = llikV,
    from = xrange[1],
    to = xrange[2],
    xlim = xrange,
    xlab = parameter,
    ylab = "log Lik",
    main = "Log Lik"
  )

  # Plot the derivative
  graphics::curve(
    expr = f,
    from = xrange[1],
    to = xrange[2],
    xlim = xrange,
    xaxt = "n",
    xlab = parameter,
    ylab = "derivative",
    main = "Newton-Raphson Algorithm \n on the derivative"
  )

  graphics::points(x, y, col = "Red", pch = 19, cex = 1.5)
  graphics::axis(1, at = x, labels = round(x, 2), las = 2)
  graphics::abline(h = 0, col = "Red")
  if (i > 1) {
    graphics::segments(x[1:(i - 1)], y[1:(i - 1)], x[2:i], rep(0, i - 1), col = "Blue", lwd = 2)
    graphics::segments(x[2:i], rep(0, i - 1), x[2:i], y[2:i], lwd = 0.5, col = "Green")
  }

  list(x = x, y = y)
}
